CREATE TABLE IF NOT EXISTS role (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  code VARCHAR(32) NOT NULL UNIQUE,
  name VARCHAR(64) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO role(code, name)
SELECT * FROM (SELECT 'ADMIN','Administrator') AS x
WHERE NOT EXISTS (SELECT 1 FROM role WHERE code='ADMIN');

INSERT INTO role(code, name)
SELECT * FROM (SELECT 'SELLER','Seller') AS x
WHERE NOT EXISTS (SELECT 1 FROM role WHERE code='SELLER');

INSERT INTO role(code, name)
SELECT * FROM (SELECT 'CLIENT','Client') AS x
WHERE NOT EXISTS (SELECT 1 FROM role WHERE code='CLIENT');
