CREATE TABLE IF NOT EXISTS refund (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  order_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  shop_id BIGINT NOT NULL,
  reason VARCHAR(500) NOT NULL,
  description LONGTEXT NULL,
  refund_amount BIGINT NOT NULL,
  currency VARCHAR(8) NOT NULL DEFAULT 'VND',
  status VARCHAR(32) NOT NULL,
  admin_note VARCHAR(1000) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  processed_at DATETIME NULL,
  version BIGINT NOT NULL DEFAULT 0,

  CONSTRAINT fk_refund_order FOREIGN KEY (order_id) REFERENCES orders(id),
  CONSTRAINT fk_refund_user FOREIGN KEY (user_id) REFERENCES app_user(id),
  CONSTRAINT fk_refund_shop FOREIGN KEY (shop_id) REFERENCES seller_shop(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
