CREATE TABLE IF NOT EXISTS role (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  code VARCHAR(32) NOT NULL UNIQUE,
  name VARCHAR(64) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO role(code, name)
SELECT * FROM (SELECT 'ADMIN' as c,'Administrator' as n) AS x
WHERE NOT EXISTS (SELECT 1 FROM role WHERE code='ADMIN');

INSERT INTO role(code, name)
SELECT * FROM (SELECT 'SELLER' as c,'Seller' as n) AS x
WHERE NOT EXISTS (SELECT 1 FROM role WHERE code='SELLER');

INSERT INTO role(code, name)
SELECT * FROM (SELECT 'CLIENT' as c,'Client' as n) AS x
WHERE NOT EXISTS (SELECT 1 FROM role WHERE code='CLIENT');
